name: dependency updates

on:
  workflow_dispatch:
  schedule:
    # Every Thursday at 10:33 (note scheduled jobs might be delayed or skipped), day later after gulag releases
    - cron: '33 10 * * 4'

jobs:
  check:
    name: Check for updated dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check for dependency updates
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: versionCatalogUpdate --no-daemon
      # Prevent the change to gradlew to be included in the PR
      - name: Revert gradlew change
        run: git checkout gradlew
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Dependency updates
          delete-branch: true
          branch: catalog-dependency-updates
          title: Dependency updates
          body: Here are some suggested updates to dependencies :)